
-- Autor: Krzysztof Szarafiński
-- nr albumu: 155441
-- Data: 12.01.2017


Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Pierwsza','Gdansk','45','1');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Druga','Gdansk','12','6');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Trzecia','Sopot','6',null);
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Czwarta','Sopot','99','5');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Piata','Gdynia','3','12');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Szosta','Gdynia','9','74');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Siodma','Tczew','69',null);
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Osma','Tczew','45',null);
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Dziewiata','Tczew','13','587');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Dziesiata','Warszawa','63','9');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Jedenasta','Warszawa','21','4');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Dwunasta','Warszawa','4',null);
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Trzynasta','Krakow','7','52');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Czternasta','Krakow','7','53');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Pietnasta','Lublin','3','99');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Szesasta','Lublin','9','12');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Siedemnasta','Poznan','1478',null);
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Osiemnasta','Poznan','16','9');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Dziewietnasta','Rzeszow','1','7');
Insert into ADRES (ULICA,MIASTO,NR_DOMU,NR_MIESZKANIA) values ('Dzwadziesta','Rzeszow','33',null);

Insert into ODDZIAL (NAZWA,EMAIL,MIASTO) values ('CENTRALA','centrala@firma.pl','Warszawa');
Insert into ODDZIAL (NAZWA,EMAIL,MIASTO) values ('GDANSK','gdansk@firma.pl','Gdansk');
Insert into ODDZIAL (NAZWA,EMAIL,MIASTO) values ('KRAKOW','krakow@firma.pl','Krakow');

Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Wiosena Promocja','5',to_date('16/03/21','RR/MM/DD'),to_date('16/05/30','RR/MM/DD'),'Promocja dajaca 5% upustu od ceny zamowienia dokonana w Q2 2016');
Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Redukcja 2016','15',to_date('16/09/12','RR/MM/DD'),to_date('16/12/20','RR/MM/DD'),null);
Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Samochod na lato','10',to_date('15/03/21','RR/MM/DD'),to_date('15/09/30','RR/MM/DD'),'Przedluzona promocja wiosenna wazna przez dwa kwartaly');
Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Loteria 2015','5',to_date('15/07/01','RR/MM/DD'),to_date('16/06/30','RR/MM/DD'),null);
Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Loteria 2016','5',to_date('16/07/01','RR/MM/DD'),to_date('17/06/30','RR/MM/DD'),null);
Insert into UPUST (NAZWA,WYSOKOSC,DATA_START,DATA_KONIEC,OPIS) values ('Total Redukcja 2014','20',to_date('14/11/11','RR/MM/DD'),to_date('16/12/16','RR/MM/DD'),null);

Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('1','1');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('1','4');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('1','5');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('2','2');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('2','3');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('2','4');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('2','5');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('2','6');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('3','1');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('3','2');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('3','4');
Insert into UPUST_ODDZIALU (ODDZIAL_ID,UPUST_ID) values ('3','5');

Insert into STANOWISKO (NAZWA) values ('Sprzedawca ');
Insert into STANOWISKO (NAZWA) values ('Asystent');
Insert into STANOWISKO (NAZWA) values ('Kierownik');
Insert into STANOWISKO (NAZWA) values ('Dyrektor');

Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Zenon','Suchy','z.suchy@firma.pl','1','1','2500');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Wieslaw','Arkonski','w.arkonski@firma.pl','2','4','9000');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Rysiek','Cywinka','r.cywinka@firma.pl','3','1','2400');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Karolina','Moskit','k.moskit@firma.pl','1','4','9000');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Paula','Nawko','p.nawko@firma.pl','2','2','1800');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Marzena','Lumbka','m.lumbka@firma.pl','3','1','2700');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Irek','Kubki','i.kubki@firma.pl','2','1','2500');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Marek','Osko','m.osko@firma.pl','2','3','3900');
Insert into SPRZEDAWCA (IMIE,NAZWISKO,EMAIL,ODDZIAL_ID,STANOWISKO_ID,PENSJA) values ('Asia','Wrobko','a.wrobko@firma.pl','3','4','7000');

Insert into STATUS_ZAMOWIENIA (NAZWA) values ('zarejestrowane');
Insert into STATUS_ZAMOWIENIA (NAZWA) values ('oczekuje na platnosc');
Insert into STATUS_ZAMOWIENIA (NAZWA) values ('gotowe do odbioru');
Insert into STATUS_ZAMOWIENIA (NAZWA) values ('nie odebrane');
Insert into STATUS_ZAMOWIENIA (NAZWA) values ('odebrane');

Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('M','Jan','Kowalski','janek99@op.pl','6');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('K','Janina','Zlota','jadzka@tlen.pl','9');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('M','Karol','Kuchta','karolcio@zonka.pl','3');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('K','Frania','Kuchta','milutka9@ty.pl','3');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('M','Slawek','Piwron','sslaw@op.pl','20');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('K','Zuza','Banko','banko.zuza@wp.pl','16');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('M','Henryk','Mirko','miroslaw@wp.pl','2');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('M','Maciej','Wirko','m.wirko@op.pl','10');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('K','Kamila','Kot','hiacynt99@interia.pl','11');
Insert into KLIENT (PLEC,IMIE,NAZWISKO,EMAIL,ADRES_ID) values ('K','Magda','Radziecka','putin@ru.pl','13');

Insert into UBEZPIECZYCIEL (NAZWA) values ('AVIVA');
Insert into UBEZPIECZYCIEL (NAZWA) values ('Generali');
Insert into UBEZPIECZYCIEL (NAZWA) values ('Hestia');
Insert into UBEZPIECZYCIEL (NAZWA) values ('PZU');
Insert into UBEZPIECZYCIEL (NAZWA) values ('UNIQA');
Insert into UBEZPIECZYCIEL (NAZWA) values ('WARTA');

Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1500',to_date('16/11/03','RR/MM/DD'),to_date('16/11/03','RR/MM/DD'),to_date('17/11/02','RR/MM/DD'),'5');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('2500',to_date('16/10/20','RR/MM/DD'),to_date('16/10/25','RR/MM/DD'),to_date('17/10/24','RR/MM/DD'),'1');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('3600',to_date('15/02/09','RR/MM/DD'),to_date('15/03/08','RR/MM/DD'),to_date('16/03/07','RR/MM/DD'),'3');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1700',to_date('16/04/16','RR/MM/DD'),to_date('16/04/16','RR/MM/DD'),to_date('17/04/15','RR/MM/DD'),'2');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1900',to_date('16/07/27','RR/MM/DD'),to_date('16/07/28','RR/MM/DD'),to_date('17/07/27','RR/MM/DD'),'6');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('2900',to_date('16/09/30','RR/MM/DD'),to_date('16/10/11','RR/MM/DD'),to_date('17/10/10','RR/MM/DD'),'4');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1200',to_date('17/01/10','RR/MM/DD'),to_date('17/01/10','RR/MM/DD'),to_date('18/01/10','RR/MM/DD'),'1');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('900',to_date('17/01/05','RR/MM/DD'),to_date('17/01/05','RR/MM/DD'),to_date('17/12/05','RR/MM/DD'),'6');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('3400',to_date('16/12/13','RR/MM/DD'),to_date('16/12/13','RR/MM/DD'),to_date('17/12/12','RR/MM/DD'),'4');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('480',to_date('16/08/20','RR/MM/DD'),to_date('16/08/20','RR/MM/DD'),to_date('17/08/19','RR/MM/DD'),'3');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1800',to_date('15/02/28','RR/MM/DD'),to_date('15/02/28','RR/MM/DD'),to_date('16/02/27','RR/MM/DD'),'2');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1300',to_date('15/06/04','RR/MM/DD'),to_date('15/06/04','RR/MM/DD'),to_date('16/06/01','RR/MM/DD'),'5');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1000',to_date('15/09/17','RR/MM/DD'),to_date('15/09/17','RR/MM/DD'),to_date('16/09/01','RR/MM/DD'),'1');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1600',to_date('16/03/12','RR/MM/DD'),to_date('16/03/12','RR/MM/DD'),to_date('17/01/10','RR/MM/DD'),'4');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('2100',to_date('16/11/30','RR/MM/DD'),to_date('16/11/30','RR/MM/DD'),to_date('17/11/08','RR/MM/DD'),'2');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1950',to_date('15/01/30','RR/MM/DD'),to_date('15/01/30','RR/MM/DD'),to_date('16/01/29','RR/MM/DD'),'6');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('700',to_date('14/11/21','RR/MM/DD'),to_date('14/11/21','RR/MM/DD'),to_date('15/11/20','RR/MM/DD'),'5');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('600',to_date('16/12/01','RR/MM/DD'),to_date('16/12/01','RR/MM/DD'),to_date('17/11/30','RR/MM/DD'),'3');
Insert into UBEZPIECZENIE (CENA,DATA_ZAWARCIA,POCZATEK,KONIEC,UBEZPIECZYCIEL_ID) values ('1540',to_date('15/05/26','RR/MM/DD'),to_date('15/05/26','RR/MM/DD'),to_date('16/05/25','RR/MM/DD'),'2');

Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('20/11/2016',to_date('16/11/03','RR/MM/DD'),to_date('16/11/13','RR/MM/DD'),'1','2','1','1');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('02/10/2016',to_date('16/10/20','RR/MM/DD'),to_date('16/10/30','RR/MM/DD'),'2','9','1','2');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('05/02/2015',to_date('15/02/09','RR/MM/DD'),to_date('15/03/29','RR/MM/DD'),'3','4','1','3');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('13/04/2016',to_date('16/04/16','RR/MM/DD'),to_date('16/05/02','RR/MM/DD'),'5','6','1','4');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('01A/07/2016',to_date('16/07/27','RR/MM/DD'),to_date('16/07/28','RR/MM/DD'),'4','3','1','5');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('01/07/2016',to_date('16/06/27','RR/MM/DD'),to_date('16/07/28','RR/MM/DD'),'3','3','1','5');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('555/01/17',to_date('17/01/10','RR/MM/DD'),to_date('17/01/17','RR/MM/DD'),'2','1','1','7');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('AKZ/12/16',to_date('17/01/05','RR/MM/DD'),to_date('17/02/16','RR/MM/DD'),'4','2','1','8');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('B/12/16',to_date('16/12/13','RR/MM/DD'),to_date('17/01/10','RR/MM/DD'),'6','3','1','9');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('04/08/2016',to_date('16/08/20','RR/MM/DD'),to_date('16/08/21','RR/MM/DD'),'9','8','1','10');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('G4A/02/2015',to_date('15/02/28','RR/MM/DD'),to_date('15/03/04','RR/MM/DD'),'10','4','1','11');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('77/06/15',to_date('15/06/04','RR/MM/DD'),to_date('15/06/04','RR/MM/DD'),'2','6','1','12');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('AA/09/2015',to_date('15/09/17','RR/MM/DD'),to_date('15/09/27','RR/MM/DD'),'4','5','1','13');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('06/03/2016',to_date('16/03/12','RR/MM/DD'),to_date('16/03/24','RR/MM/DD'),'1','7','1','14');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('117/11/2016',to_date('16/11/30','RR/MM/DD'),to_date('16/12/15','RR/MM/DD'),'3','9','1','15');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('1/01/15',to_date('15/01/30','RR/MM/DD'),to_date('15/02/14','RR/MM/DD'),'5','2','1','16');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('03/11/2014',to_date('14/11/21','RR/MM/DD'),to_date('14/11/27','RR/MM/DD'),'7','1','1','17');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('26/12/2016',to_date('16/12/01','RR/MM/DD'),to_date('16/12/23','RR/MM/DD'),'8','9','1','18');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('12/05/2015',to_date('15/05/26','RR/MM/DD'),to_date('15/06/12','RR/MM/DD'),'3','6','1','19');
Insert into ZAMOWIENIE (NR_UMOWY,DATA_ZAWARCIA,DATA_ODBIORU,KLIENT_ID,SPRZEDAWCA_ID,STATUS_ZAMOWIENIA_ID,UBEZPIECZENIE_ID) values ('16/08/16',to_date('16/08/16','RR/MM/DD'),to_date('16/08/31','RR/MM/DD'),'1','4','1','10');

Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('pakiet zimowych opon','1500');
Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('voucher na myjnie na rok','1000');
Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('przechowywanie opon','70');
Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('hotel samochodowy','2000');
Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('przeglad','400');
Insert into USLUGI_DODATKOWE (NAZWA,CENA) values ('serwis klimatyzacji','100');

Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('1','1');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('1','6');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('4','2');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('6','5');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('8','6');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('9','1');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('12','4');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('14','1');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('16','2');
Insert into WYBRANE_USLUGI (ZAMOWIENIE_ID,USLUGI_DODATKOWE_ID) values ('20','3');

Insert into RODZAJ_PLATNOSCI (NAZWA) values ('gotowka');
Insert into RODZAJ_PLATNOSCI (NAZWA) values ('karta');
Insert into RODZAJ_PLATNOSCI (NAZWA) values ('kredyt');
Insert into RODZAJ_PLATNOSCI (NAZWA) values ('przelew');

Insert into STATUS_PLATNOSCI (NAZWA) values ('zaksiegowana');
Insert into STATUS_PLATNOSCI (NAZWA) values ('nadplata');
Insert into STATUS_PLATNOSCI (NAZWA) values ('do zwrotu');

Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/10/28','RR/MM/DD'),'1000',null,'1','1','2','2');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/05/16','RR/MM/DD'),'20000',null,'1','2','5','4');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('17/01/06','RR/MM/DD'),'30000',null,'1','3','4','8');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('17/01/10','RR/MM/DD'),'2000',null,'1','4','2','7');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/04/12','RR/MM/DD'),'500000',null,'1','1','1','14');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/12/13','RR/MM/DD'),'6000',null,'1','2','6','9');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('15/06/04','RR/MM/DD'),'30000',null,'1','2','2','12');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/11/30','RR/MM/DD'),'14520',null,'1','1','3','15');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('15/02/28','RR/MM/DD'),'1452',null,'1','3','10','11');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/06/27','RR/MM/DD'),'169752',null,'1','1','3','6');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('15/09/17','RR/MM/DD'),'42609',null,'1','2','4','13');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/08/16','RR/MM/DD'),'24587',null,'1','4','1','20');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/12/01','RR/MM/DD'),'86542',null,'1','1','8','18');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('15/02/09','RR/MM/DD'),'11258',null,'1','2','8','3');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/10/29','RR/MM/DD'),'1000',null,'1','1','2','2');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/10/30','RR/MM/DD'),'1000',null,'1','1','2','2');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/10/31','RR/MM/DD'),'1000',null,'1','1','2','2');
Insert into PLATNOSC (DATA_DOKONANIA,KWOTA,UWAGI_DODATKOWE,STATUS_PLATNOSCI_ID,RODZAJ_PLATNOSCI_ID,KLIENT_ID,ZAMOWIENIE_ID) values (to_date('16/10/31','RR/MM/DD'),'70000',null,'1','1','2','2');

Insert into WYPOSAZENIE (NAZWA) values ('Poduszki powietrzne czolowe dla kierowcy i pasazera');
Insert into WYPOSAZENIE (NAZWA) values ('Poduszki powietrzne boczne dla kierowcy i pasazera, pelnowymiarowe kurtyny powietrzne');
Insert into WYPOSAZENIE (NAZWA) values ('Pasy bezpieczenstwa z napinaczami (przod) oraz czujnikami obecnosci pasazera (przod/ tyl)');
Insert into WYPOSAZENIE (NAZWA) values ('ESC - System stabilizacji toru jazdy');
Insert into WYPOSAZENIE (NAZWA) values ('TCS - System kontroli trakcji, ');
Insert into WYPOSAZENIE (NAZWA) values ('HAC - System wspomagajacy pokonywanie podjazdow');
Insert into WYPOSAZENIE (NAZWA) values ('VSM - System podpowiedzi ruchu kierownicy');
Insert into WYPOSAZENIE (NAZWA) values ('ABS - System zapobiegajacy blokowaniu sie kol podczas hamowania ');
Insert into WYPOSAZENIE (NAZWA) values ('EBD - System rozdzialu sily hamowania');
Insert into WYPOSAZENIE (NAZWA) values ('BAS - System wspomagania hamowania');
Insert into WYPOSAZENIE (NAZWA) values ('ESS - System automatycznego wlaczania swiatel awaryjnych podczas gwaltownego hamowania');
Insert into WYPOSAZENIE (NAZWA) values ('Hamulce tarczowe przod i tyl');
Insert into WYPOSAZENIE (NAZWA) values ('swiatla mijania typu projekcyjnego');
Insert into WYPOSAZENIE (NAZWA) values ('Tylny spojler');
Insert into WYPOSAZENIE (NAZWA) values ('swiatla do jazdy dziennej wkomponowane w zderzak przedni');
Insert into WYPOSAZENIE (NAZWA) values ('Przednie lampy przeciwmgielne');
Insert into WYPOSAZENIE (NAZWA) values ('Czujniki parkowania tylem');
Insert into WYPOSAZENIE (NAZWA) values ('Elektryczne, progresywne wspomaganie ukladu kierowniczego, Regulacja kolumny kierownicy.');
Insert into WYPOSAZENIE (NAZWA) values ('System informacyjny: aktualna data i godzina, temperatura zewnetrzna, sygnalizacja otwartych drzwi');
Insert into WYPOSAZENIE (NAZWA) values ('Komputer pokladowy: pokonany dystans, zuzycie paliwa, czas jazdy, zasieg');
Insert into WYPOSAZENIE (NAZWA) values ('Elektrycznie sterowane szyby drzwi przednich');
Insert into WYPOSAZENIE (NAZWA) values ('Elektrycznie regulowane lusterka zewnetrzne');
Insert into WYPOSAZENIE (NAZWA) values ('Radioodtwarzacz CD MP3 z funkcja sterowania w kole kierownicy');
Insert into WYPOSAZENIE (NAZWA) values ('Bluetooth z zestawem glosnomowiacym');
Insert into WYPOSAZENIE (NAZWA) values ('Alarm obwodowy');
Insert into WYPOSAZENIE (NAZWA) values ('immobilizer');
Insert into WYPOSAZENIE (NAZWA) values ('Funkcja zdalnego sterowania centralnym zamkiem, automatyczne ryglowanie zamkow po ruszeniu');
Insert into WYPOSAZENIE (NAZWA) values ('Klimatyzacja manualna z funkcja chlodzenia schowka');
Insert into WYPOSAZENIE (NAZWA) values ('Podgrzewane lusterka zewnetrzne, lakierowane w kolorze nadwozia');
Insert into WYPOSAZENIE (NAZWA) values ('Centralny podlokietnik tylnej kanapy z uchwytami na kubki');
Insert into WYPOSAZENIE (NAZWA) values ('system nawigacji satelitarnej z obsluga w jezyku polskim, ');
Insert into WYPOSAZENIE (NAZWA) values ('Lampka do czytania w podsufitce oraz schowek na okulary');
Insert into WYPOSAZENIE (NAZWA) values ('Elektrycznie sterowane szyby drzwi przednich i tylnych z funkcja bezpieczenstwa');
Insert into WYPOSAZENIE (NAZWA) values ('lektrycznie skladane lusterka zewnetrzne z funkcja kierunkowskazow');
Insert into WYPOSAZENIE (NAZWA) values ('Elektrochromatyczne lusterko wewnetrzne');
Insert into WYPOSAZENIE (NAZWA) values ('system podgrzewania wycieraczek');
Insert into WYPOSAZENIE (NAZWA) values ('system otwierania i uruchamiania pojazdu bez uzycia kluczyka');
Insert into WYPOSAZENIE (NAZWA) values ('Dwie chromowane koncowki ukladu wydechowego');
Insert into WYPOSAZENIE (NAZWA) values ('podswietlenie klamek zewnetrznych drzwi przednich');
Insert into WYPOSAZENIE (NAZWA) values ('Aluminiowe nakladki na pedaly');
Insert into WYPOSAZENIE (NAZWA) values ('Sportowa stylistyka zderzakow');
Insert into WYPOSAZENIE (NAZWA) values ('Podgrzewane lusterka zewnetrzne, lakierowane w kolorze nadwozia');

Insert into KLASA_WYPOSAZENIA (NAZWA,OPIS) values ('S','small');
Insert into KLASA_WYPOSAZENIA (NAZWA,OPIS) values ('M','medium');
Insert into KLASA_WYPOSAZENIA (NAZWA,OPIS) values ('L','large');
Insert into KLASA_WYPOSAZENIA (NAZWA,OPIS) values ('GT','sport');

Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('1','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('1','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('1','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('1','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('2','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('2','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('2','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('2','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('3','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('3','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('3','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('3','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('4','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('4','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('4','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('4','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('5','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('5','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('5','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('5','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('6','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('6','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('6','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('6','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('7','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('7','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('7','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('7','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('8','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('8','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('8','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('8','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('9','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('9','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('9','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('9','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('10','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('10','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('10','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('10','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('11','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('11','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('11','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('11','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('12','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('12','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('12','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('12','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('13','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('13','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('13','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('13','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('14','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('14','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('14','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('14','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('15','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('15','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('15','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('15','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('16','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('16','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('16','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('17','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('17','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('18','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('18','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('18','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('18','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('19','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('19','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('19','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('19','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('20','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('20','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('20','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('20','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('21','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('21','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('21','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('21','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('22','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('22','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('22','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('22','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('23','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('23','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('23','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('23','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('24','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('24','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('24','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('24','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('25','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('25','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('25','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('25','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('26','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('26','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('26','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('26','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('27','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('27','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('27','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('27','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('28','1');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('28','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('29','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('29','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('29','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('30','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('30','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('31','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('31','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('31','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('32','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('32','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('32','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('33','2');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('33','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('33','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('34','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('34','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('35','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('35','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('36','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('36','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('37','3');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('37','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('38','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('39','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('40','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('41','4');
Insert into PAKIET_PODSTAWOWY (WYPOSAZENIE_ID,KLASA_WYPOSAZENIA_ID) values ('42','4');

Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Fresh Air','Wnetrze samochodu wyposazonego w pakiet AIR-BALANCE mozna indywidualnie aromatyzowac. W zaleznosci od osobistych preferencji lub nastroju dostepne sa cztery szlachetne zapachy. Jonizowane powietrze, klimatyzacja','4000');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Schowkow','Pakiet schowkow zawiera dodatkowe schowki i mocowania we wnetrzu auta oraz w bagazniku. Schowek pod lokietnikiem. Z tylu kieszenie na oparciach foteli ','3000');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Antykradziezowy','Alarm antykradziezowy ostrzega o wlamaniu do samochodu i kradziezy. System aktywowany jest przy zamykaniu samochodu pilotem zdalnego sterowania. Funkcja zabezpieczenia przed odholowaniem reaguje na zmiane polozenia pojazdu.','1000');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Bezpieczeny','Polaczenie systemow bezpieczenstwa i wspomagania odciaza kierowce, zmniejsza ryzyko wypadku oraz chroni pasazerow. Aktywny asystent utrzymania pasa ruchu oraz aktywny asystent martwego punktu ','3500');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Smart Light','Obejmuje on posrednie oswietlenie obszaru przy podlodze i wnek klamek, podswietlane elementy na konsoli srodkowej, lampki do czytania z tylu oraz podswietlane lusterko do makijazu.','2300');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Parkowania','Aktywny asystent parkowania z systemem PARKTRONIC ulatwia zarowno wyszukiwanie miejsc parkingowych polozonych rownolegle lub prostopadle do jezdni, jak i zaparkowanie i wyparkowanie. ','1900');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Komfortowy','Klimatyzacja automatyczna dwustrefowa z 2 trybami pracy: SOFT i FAST oraz filtrem, przeciwpylkowym, jonizatorem powietrza, systemem automatycznego odparowywania przedniej szyby, funkcja
chlodzenia schowka','2500');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Funkcjonalny','Wzbogacona iluminacja i wyglad zegarow deski rozdzielczej Kia Supervision Clusterr z wyswietlaczem LCD - wskazania aktualnej predkosci, informacji z czujnikow cofania, komputera pokladowego oraz ustawien systemowych auta','2500');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Techniczny','system monitorowania ruchu pojazdow podczas cofania, system monitorowania martwego pola w lusterkach, Automatyczny system
parkowania rownoleglego i prostopadlego ','4000');
Insert into PAKIET_DODATKOWY (NAZWA,OPIS,CENA) values ('Pakiet Ratunkowy','System ratunkowy. Automatyczne: rozpoznanie wypadku, wezwanie sluzb ratowniczych, pomoc na zadanie, rejestracja parametrow wypadku, wezwanie assistance','3390');

Insert into MARKA (NAZWA,KRAJ) values ('VOLKSWAGEN','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('OPEL','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('RENAULT','Francja');
Insert into MARKA (NAZWA,KRAJ) values ('AUDI','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('FORD','USA');
Insert into MARKA (NAZWA,KRAJ) values ('MERCEDES','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('BMW','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('PEUGEOT','Francja');
Insert into MARKA (NAZWA,KRAJ) values ('CITROEN','Francja');
Insert into MARKA (NAZWA,KRAJ) values ('SEAT','Niemcy');
Insert into MARKA (NAZWA,KRAJ) values ('KIA','Korea Poludniowa');
Insert into MARKA (NAZWA,KRAJ) values ('Hyundai','Korea Poludniowa');
Insert into MARKA (NAZWA,KRAJ) values ('Volvo','Szwecja');
Insert into MARKA (NAZWA,KRAJ) values ('Honda','Japonia');
Insert into MARKA (NAZWA,KRAJ) values ('Mazda','Japonia');

Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Pasat','1','2016','3','26252.15','4');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('A4','4','2014','4','59665.75','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('A6','4','2006','1','34436.31','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Astra','2','2016','1','51464.3','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Ceed','11','2013','4','49710.53','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('6','15','2010','2','42624.84','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Mondeo','5','2012','1','50402.24','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Laguna','2','1998','2','56581.31','2');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Vectra','3','2015','1','30287.01','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Civic','14','1998','2','42013.95','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Jazz','14','2014','4','34395.18','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('C5','9','2016','3','47810.45','4');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('306','8','2015','3','24734.28','4');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('V40','13','2016','1','59196.62','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Cordoba','10','2014','4','47810.36','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('A','6','2015','3','41948.06','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('B','6','2015','3','43324.58','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('C','6','2015','3','36694.53','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Golf','1','2014','4','76541.32','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('3','15','2011','2','36541.32','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('i30','12','2006','1','46789.21','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('i40','12','2013','1','63247.87','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Ceed','11','2014','4','78523.12','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Sportage','11','2009','2','96347.21','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Ibiza','10','2015','1','47856.12','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Toledo','10','2016','1','74521.3','4');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('C3','9','2010','3','48759.88','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('301','8','2012','1','90125.36','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('i3','7','2016','3','102654.33','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('i8','7','2014','3','120001.66','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('C-max','5','2013','2','40654.98','4');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Fiesta','5','2000','4','30012.99','2');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Clio','3','2014','1','23541','3');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('Clio','3','2015','4','80000','5');
Insert into MODEL (NAZWA,MARKA_ID,ROK_PRODUKCJI,KLASA_WYPOSAZENIA_ID,CENA,LICZBA_DRZWI) values ('i30','12','2013','4','70096.22','5');

Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('BENZYNA','1598','5000');
Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('BENZYNA','1624','8000');
Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('BENZYNA','1799','10000');
Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('DIESEL','1686','9000');
Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('DIESEL','1994','11000');
Insert into SILNIK (TYP,POJEMNOSC,CENA) values ('DIESEL','2171','12000');

Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('bialy','biel alpejska','200');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('niebieski','blekit krolewski','600');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('czerwony','czerwien rubinu','700');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('niebieski','blekit malte','300');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('braz','braz kasztanowy','1100');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('braz','bez popielaty','600');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('czarny','czarny etoile','1000');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('szary','platynowy','750');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('szary','szary kasjopea','960');
Insert into KOLOR (NAZWA,ODCIEN,CENA) values ('czarny','eclipse','1140');

Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('KMHTC6AD3FU230508','648','2','34','1','10');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1VWBV7A36FC040227','1084','3','25','5','7');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('2GNALBEK7F6118474','1921','1','20','4','6');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1GCEK19K0SE133793','286','4','31','6','9');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1G1ZA5EU7BF150662','2952','5','13','3','4');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('3GCEC23069G244460','682','6','17','4','5');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FM5K8GT9FGA51717','986','7','12','3','3');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('2G1FB1ED9B9115736','2391','8','2','1','1');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1GCSKREA0AZ259108','585','9','12','3','4');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1GKS1HE04BR217941','1624','10','22','5','6');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('5ZVBE1423AD003776','1927','11','4','2','1');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('2HNYD2H81DH505716','2508','12','28','6','8');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('5TFJX4CN6BX008905','527','13','1','1','10');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('JHLRE48508C010699','2924','14','14','3','4');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1C6RR6GT4ES179209','2725','15','26','5','7');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1N4AA5AP5BC812041','2729','16','29','6','8');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('KNAGM4AD0D5044856','2087','17','34','1','10');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('WBA3C1C5XFP852323','1368','18','8','2','2');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1XKADB8X26J092113','172','19','22','5','6');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FTPW14V99FB39420','2661','20','11','3','3');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FTFW1ET2DKG44594','682','1','30','6','8');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('WMWMF73598TV33097','572','2','33','1','9');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('WVWMA23B7YP355662','1546','13','18','4','5');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FTPW14514KC03224','2357','14','3','1','1');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('3VWFW31C98M510694','2165','15','8','2','2');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FM5K7F88EGA60690','100',null,'35','6','5');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1FT7X2BT4BEC19899','2',null,'11','1','1');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('WA1UFAFL4DA229069','3',null,'7','4','9');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('KMHCT4AE6FU822000','40',null,'3','3','7');
Insert into SAMOCHOD (NR_VIN,PRZEJECHANY_DYSTANS,ZAMOWIENIE_ID,MODEL_ID,SILNIK_ID,KOLOR_ID) values ('1N4BL2AP4CC152492','60',null,'6','2','3');

Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('3','3');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('4','2');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('4','4');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('4','6');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('6','8');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('7','7');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('8','1');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('8','3');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('10','1');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('10','5');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('10','10');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('11','5');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('11','9');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('12','4');
Insert into WYBRANE_PAKIETY (SAMOCHOD_ID,PAKIET_DODATKOWY_ID) values ('17','4');